books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail'),
]

bookstore/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from bookstore import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^books/', include('books.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^search/', include('search.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.conf.urls import url
from . import views

app_name = 'feedback'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

news/urls.py
from django.conf.urls import url
from . import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

search/urls.py
from django.conf.urls import url
from . import views

app_name = 'search'
urlpatterns = [
    url(r'^$', views.search, name='search'),
]

books/models.py
import os
from django.db import models


def get_image_path(instance, filename):
    return os.path.join('photos', str(instance.id), filename)


class Book(models.Model):
    name = models.CharField(max_length=255, unique=True)
    author = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    amount = models.PositiveIntegerField()
    photo = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.name

feedback/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

news/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.utils.translation import pgettext


class News(models.Model):
    spoiler = models.CharField(max_length=255)
    content = models.TextField()
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.spoiler

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    class Meta:
        verbose_name = pgettext("news singular", "news")
        verbose_name_plural = pgettext("news plural", "news")

search/models.py
from django.db import models

# Create your models here.

books/forms.py
from django import forms
from captcha.fields import CaptchaField
from django.core.mail import send_mail
from django.template.loader import render_to_string

from bookstore.private_settings import EMAIL_TO, EMAIL_HOST_USER


class BookOrderForm(forms.Form):
    email = forms.EmailField(label='Email', required=True)
    amount = forms.IntegerField(label='Количество', required=True)
    captcha = CaptchaField(label='Введите капчу', required=True)

    def send_email(self, book):
        context = {
            'book': book,
            'amount': self.cleaned_data['amount'],
            'email': self.cleaned_data['email'],
        }
        send_mail(
            'Заказ книги',
            render_to_string('books/email.txt', context),
            EMAIL_HOST_USER,
            [EMAIL_TO],
            fail_silently=False,
            html_message=render_to_string('books/email.html', context)
        )

feedback/forms.py
from django import forms
from captcha.fields import CaptchaField
from django.core.mail import send_mail
from django.template.loader import render_to_string

from bookstore.private_settings import EMAIL_HOST_USER, EMAIL_TO


class FeedbackForm(forms.Form):
    email = forms.EmailField(label='Email', required=True)
    message = forms.CharField(widget=forms.Textarea, label='Ваше сообщение',
                              required=True)
    captcha = CaptchaField(label='Введите капчу', required=True)

    def send_email(self):
        context = {
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        send_mail(
            'Сообщение с формы обратной связи',
            render_to_string('feedback/email.txt', context),
            EMAIL_HOST_USER,
            [EMAIL_TO],
            fail_silently=False,
            html_message=render_to_string('feedback/email.html', context)
        )

books/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Book
from .forms import BookOrderForm


class IndexView(generic.ListView):
    template_name = 'books/index.html'
    context_object_name = 'books'

    def get_queryset(self):
        return Book.objects.filter(amount__gt=0)


def detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    form = BookOrderForm()

    if request.method == 'POST':
        form = BookOrderForm(data=request.POST)

        if form.is_valid():
            form.send_email(book)
            messages.info(request, 'Ваш заказ успешно принят')
            return HttpResponseRedirect(reverse('books:index'))

    return render(request, 'books/detail.html', {'form': form, 'book': book})

feedback/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import FeedbackForm


def index(request):
    if request.method == 'POST':
        form = FeedbackForm(data=request.POST)

        if form.is_valid():
            form.send_email()
            messages.info(request, 'Ваше сообщение успешно отправлено')
            return HttpResponseRedirect(reverse('home:index'))
    else:
        form = FeedbackForm()

    return render(request, 'feedback/index.html', {'form': form})

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

news/views.py
from django.views import generic
from django.utils import timezone

from .models import News


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = 'latest_news'

    def get_queryset(self):
        return News.objects.filter(pub_date__lte=timezone.now())\
            .order_by('-pub_date')


class DetailView(generic.DetailView):
    model = News
    template_name = 'news/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return News.objects.filter(pub_date__lte=timezone.now())

search/views.py
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from books.models import Book
from news.models import News


def search_books(query, results):
    search_results = Book.objects.filter(
        Q(name__icontains=query)
        | Q(description__icontains=query)
        | Q(author__icontains=query)
    )
    for result in search_results:
        results.append({
            'url': reverse('books:detail', args=[result.id]),
            'header': 'Книга: {}'.format(result.name),
        })


def search_news(query, results):
    search_results = News.objects.filter(
        Q(spoiler__icontains=query) | Q(content__icontains=query)
    )
    for result in search_results:
        results.append({
            'url': reverse('news:detail', args=[result.id]),
            'header': 'Новость: {}'.format(result.spoiler),
        })


def search(request):
    query = request.POST['query']

    if not query:
        messages.error(request, 'Вы указали пустое значение для поиска')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    results = []
    search_books(query, results)
    search_news(query, results)

    return render(request, 'search/results.html', {
        'query': query,
        'results': results,
    })

books/templates/books/base.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}" />
{% endblock %}

books/templates/books/detail.html
{% extends 'books/base.html' %}

{% load bootstrap %}

{% block title %}{{ block.super }} | {{ book.name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            {% include 'books/partials/book.html' %}
        </div>
        <div class="col-sm-4">

            <form action="{% url 'books:detail' book.id %}" method="post">
                {% csrf_token %}

                {{ form|bootstrap }}

                <input type="submit" class="btn btn-primary" value="Заказать"/>
            </form>
        </div>
    </div>
{% endblock %}

books/templates/books/email.html
<h2>Заказ книги "{{ book.name }}"</h2>
<div>
    Пользователь с email {{ email }} заказал книгу "{{ book.name }}" в количестве
    {{ amount }}
</div>

books/templates/books/index.html
{% extends 'books/base.html' %}

{% block title %}{{ block.super }} | Книги{% endblock %}

{% block content %}
    {% if books %}
        <div class="books-page">
            <div class="page-header">
                <h1>Книги</h1>
            </div>
            {% include 'books/partials/books.html' with books=books %}
        </div>
    {% else %}
        <p>На данный момент в нашем магазине нет книг</p>
    {% endif %}
{% endblock %}

books/templates/books/partials/book.html
<div class="book">
    <img src="{{ book.photo.url }}">
    <h2>{{ book.name }}</h2>
    <p>Автор: {{ book.author }}</p>
    <p>Цена: {{ book.price }} руб.</p>
    <p>{{ book.description }}</p>
</div>

books/templates/books/partials/books.html
{% load chunks %}

{% for chunk in books|chunks:2 %}
    <div class="row">
        {% for book in chunk %}
            <div class="col-sm-6 books-page__book">
                <a href="{% url 'books:detail' book.id %}">
                    <div class="media">
                        <div class="media-left">
                            {% if book.photo %}
                                <img class="media-object" src="{{ book.photo.url }}">
                            {% endif %}
                        </div>
                        <div class="media-body">
                            <h2 class="media-heading">{{ book.name }}</h2>
                            <p>Автор: {{ book.author }}</p>
                            <p>Цена: {{ book.price }} руб.</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endfor %}

feedback/templates/feedback/email.html
<h2>Форма обратной связи</h2>
<div>
    Пользователь с email {{ email }} оставил следующее сообщение в форме обратной связи:
    <p>
        "{{ message }}"
    </p>
</div>

feedback/templates/feedback/index.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block title %}{{ block.super }} | Обратная связь{% endblock %}

{% block content %}
    <h2>Обратная связь</h2>

    <form action="{% url 'feedback:index' %}" method="post">
        {% csrf_token %}

        {{ form|bootstrap }}

        <input type="submit" class="btn btn-primary" value="Отослать"/>
    </form>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <h1>Магазин книг</h1>
        <p>Здесь вы можете найти и заказать интересущие вас книги</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'books:index' %}" role="button">В каталог книг</a></p>
    </div>
{% endblock %}

news/templates/news/detail.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} | {{ news.spoiler }}{% endblock %}

{% block content %}
    <h1 class="well">{{ news.spoiler }}</h1>
    <p>{{ news.pub_date }}</p>
    <p>{{ news.content }}</p>
{% endblock %}

news/templates/news/index.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} | Новости{% endblock %}

{% block content %}
    {% if latest_news %}
        <div class="page-header">
            <h1>Новости</h1>
        </div>
        {% for news in latest_news %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-10">
                                <h2><a href="{% url 'news:detail' news.id %}">{{ news.spoiler }}</a></h2>
                            </div>
                            <div class="col-sm-2">
                                <p>{{ news.pub_date }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>Пока что новостей нет</p>
    {% endif %}
{% endblock %}

search/templates/search/results.html
{% extends 'books/base.html' %}

{% block title %}{{ block.super }} | Результаты поиска{% endblock %}

{% block content %}
    {% if results %}
        <div class="page-header">
            <h1>Результаты поиска по запросу "{{ query }}"</h1>
        </div>
        {% for result in results %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2><a href="{{ result.url }}">{{ result.header }}</a></h2>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>Ничего не нашлось</p>
    {% endif %}
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    {% endblock %}

    <title>{% block title %}Магазин книг{% endblock %}</title>
</head>

<body>
<div class="container">
    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    {% block content %}{% endblock %}
</div>

<script src="{% static 'jquery/dist/jquery.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.js' %}"></script>
</body>
</html>

templates/captcha/field.html
<div class="captcha-image">{{ image }}</div>
{{ hidden_field }}{{ text_field }}

templates/captcha/text_field.html
<input class="form-control" autocomplete="off" id="{{id}}_1" name="{{name}}_1" type="text" />

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#app-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Магазин книг</a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Главная</a></li>
                <li><a href="{% url 'books:index' %}">Книги</a></li>
                <li><a href="{% url 'news:index' %}">Новости</a></li>
                <li><a href="{% url 'feedback:index' %}">Обратная связь</a></li>
            </ul>

            <form class="navbar-form navbar-right"
                  action="{% url 'search:search' %}" method="POST">
                {% csrf_token %}

                <div class="form-group">
                    <input type="text" class="form-control"
                           placeholder="Поиск по сайту" name="query">
                </div>

                <button type="submit" class="btn btn-default">Искать</button>
            </form>
        </div>
    </div>
</nav>